### PR TITLE
Add support to generate .ensime files for Android

### PR DESCRIPTION
**Pull request by rolandtritsch**

### CODE REVIEW

**Comment by rolandtritsch** [comment]
Hi Bill, can you please merge this and publish a new package. Thanks in advance. - RT

**Comment by rolandtritsch** [comment]
Hi Bill, one other thought ... if you are too busy to do the merge then feel free to make me a collaborator on the repository and I can do the merge for you. - RT

**Comment by coacoas** [comment]
Sorry it took so long. The code is merged and a new release (0.1.11) has been pushed to central. I also made you a collaborator so that this doesn't happen again. Also, the Java 8 requirement should now be gone. 

Thanks for your patience.

**Comment by rolandtritsch** [comment]
Perfect. Just tested it. It works. - RT

On 4 March 2015 at 16:32, Bill Carlson <notifications@github.com> wrote:

> Sorry it took so long. The code is merged and a new release (0.1.11) has
> been pushed to central. I also made you a collaborator so that this doesn't
> happen again. Also, the Java 8 requirement should now be gone.
>
> Thanks for your patience.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coacoas/gradle-ensime/pull/6#issuecomment-77191922>.
>



-- 
e: roland@tritsch.org
m: +353-86-8563975
s: rolandtritsch
---
http://trits.ch/rt-qr-code
http://trits.ch/rt-linked-in
http://www.tritsch.org

**Pull request merged**
